### PR TITLE
Use default system dirs for app files

### LINKED ISSUE #512: [FEATURE] Use default system dirs
**Is your feature request related to a problem? Please describe.**
Applications should keep their cache/config files in default system directories. E.g. for Linux there is [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) which tells that cache should be stored in `~/.cache/<app>` dir, config files in `~/.config/<app>` dir and so on.
I guess other OSes have their own rules, see https://github.com/platformdirs/platformdirs#example-output

**Describe the solution you'd like**
Save `config.yaml` in user config dir, `download_history.sqlite` in user data dir, `downloader.log` in user log dir, `internal_variable_cache.yaml` in user cache dir and so on.
Add new flag, e.g. `--portable` to keep all files in current run dir.
If files exist in current run dir they should override files in user dirs, i.e. do not open `/user_config_dir/config.yaml` if `config.yaml` exists in current dir.

### PR DESCRIPTION
**Pull request by qarkai**
I consider following distribution:
variable_cache_file -> user cache dir
config_file -> user config dir
db_file -> user data dir
errored_download_urls_file, errored_scrape_urls_file, log_file, unsupported_urls_file -> user log dir
output_last_forum_post_file -> user state dir
Not sure about output_last_forum_post_file. It seems we never read it.
I'm open to suggestions about files to dirs distribution.

Also I haven't update Pipfile.lock since I don't use Pipfile and don't know how to do it.

Fix #512.

### CODE REVIEW

**Comment by Jules-WinnfieldX** [comment]
I know this is the proper way things should be... I am however worried about the tech illiterate people that use this, and me helping troubleshoot. I'd prefer if it was portable by default.

**Comment by Jules-WinnfieldX** [comment]
I might need to sit and think on this for a while

**Comment by Jules-WinnfieldX** [comment]
So. My thoughts on this are that it would be bad for my mental health lmao.

The only way I could see this working for me is changing the --portable tag to --use-sys-dirs. People are stupid, and having the defaults be sys directories will be hell for me in answering questions and troubleshooting for ignorant users. More so than it already is. 

There are files I could definitely see being able to move to sys dirs without worry, such as the db and cache file. But things such as the downloader.log and config file is where my worries arise.

**Comment by qarkai** [comment]
Not a problem, I'll change flag logic. Would it be okay to move db and cache independently of it?

**Comment by Jules-WinnfieldX** [comment]
Yea, lets move those two regardless.

**Comment by Jules-WinnfieldX** [comment]
Might be worth also putting them in a Cyberdrop-DL folder in the sys folders.

**Comment by qarkai** [comment]
> unless a path is provided for it of course

I check if path is not absolute. Do you mean compare it with default value?

**Comment by Jules-WinnfieldX** [comment]
No, how that is should be good. May also need a check for relative paths though.

**Comment by Jules-WinnfieldX** [comment]
Hey Qark, just checking before I merge this, did you test this? All working good?

**Comment by qarkai** [comment]
I use this branch on my Linux machine, everything works fine.

**Comment by qarkai** [comment]
@Jules-WinnfieldX just to be clear, is there anything you wait from me here?

**Comment by Jules-WinnfieldX** [comment]
No, your good. Just on vacation again. I'll get to this monday most likely

**Comment by Jules-WinnfieldX** [comment]
It's gonna be this week, I swear. I just want some proper time to look through this and figure out where files are going, etc.

**Pull request merged**
