### PR TITLE
Remove url_path parameter from *Downloader.download_file

### PR DESCRIPTION
**Pull request by qarkai**
Get its value using remaining parameters.

### CODE REVIEW

**Comment by Jules-WinnfieldX** [comment]
This is one I'll have to reject. It doesn't seem like it at first glance, but there are a couple crawlers that get the URL_Path from differing sources. It's not always the media.url. GoFile for instance is the media.referer. I don't think it's the only one, but I prefer passing in variables than doing domain specific work in something like the downloader.

**Comment by qarkai** [comment]
> It's not always the media.url

I didn't mean using `MediaItem.url`. Just some `URL`. It could be crawler's `url` parameter like https://github.com/Jules-WinnfieldX/CyberDropDownloader/blob/0140bbdc0492812be82b3887faab341f5281e498/cyberdrop_dl/crawlers/GoFile_Spider.py#L46
It could be url constructed in crawler like https://github.com/Jules-WinnfieldX/CyberDropDownloader/blob/0140bbdc0492812be82b3887faab341f5281e498/cyberdrop_dl/crawlers/GoFile_Spider.py#L92
Could be other. Main idea is that crawlers know only URL info. Its representation in database should be known by database-related code.

**Comment by Jules-WinnfieldX** [comment]
Are you suggesting creating a reference link for the MediaItem that would be used for the URL_Path later? Or something else here?

I don't disagree that it should belong there, just trying to think of cleanliness. V3 had domain specific hotfixes pretty much everywhere and it was a large motivation for the rewrite to V4

**Comment by qarkai** [comment]
I'll create draft PR with sample change. I hope it's more clear than my description.

**Comment by qarkai** [comment]
See #379

**Comment by qarkai** [comment]
This change requires adding same logic to `retry`. It increase complexity.

**Pull request closed without merging**
